# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import hello_service_pb2 as hello__service__pb2

GRPC_GENERATED_VERSION = '1.75.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in hello_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MultilingualGreeterStub(object):
    """The greeting service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SayHello = channel.unary_unary(
                '/hello.MultilingualGreeter/SayHello',
                request_serializer=hello__service__pb2.HelloRequest.SerializeToString,
                response_deserializer=hello__service__pb2.HelloResponse.FromString,
                _registered_method=True)
        self.SayHellosServerStreaming = channel.unary_stream(
                '/hello.MultilingualGreeter/SayHellosServerStreaming',
                request_serializer=hello__service__pb2.HelloRequest.SerializeToString,
                response_deserializer=hello__service__pb2.HelloResponse.FromString,
                _registered_method=True)
        self.SayHellosClientStreaming = channel.stream_unary(
                '/hello.MultilingualGreeter/SayHellosClientStreaming',
                request_serializer=hello__service__pb2.HelloRequest.SerializeToString,
                response_deserializer=hello__service__pb2.HelloResponse.FromString,
                _registered_method=True)
        self.SayHellosBidirectional = channel.stream_stream(
                '/hello.MultilingualGreeter/SayHellosBidirectional',
                request_serializer=hello__service__pb2.HelloRequest.SerializeToString,
                response_deserializer=hello__service__pb2.HelloResponse.FromString,
                _registered_method=True)


class MultilingualGreeterServicer(object):
    """The greeting service definition.
    """

    def SayHello(self, request, context):
        """Unary RPC - Simple request/response
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SayHellosServerStreaming(self, request, context):
        """Server streaming RPC - Server sends multiple responses
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SayHellosClientStreaming(self, request_iterator, context):
        """Client streaming RPC - Client sends multiple requests
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SayHellosBidirectional(self, request_iterator, context):
        """Bidirectional streaming RPC - Both sides send a sequence of messages
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MultilingualGreeterServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SayHello': grpc.unary_unary_rpc_method_handler(
                    servicer.SayHello,
                    request_deserializer=hello__service__pb2.HelloRequest.FromString,
                    response_serializer=hello__service__pb2.HelloResponse.SerializeToString,
            ),
            'SayHellosServerStreaming': grpc.unary_stream_rpc_method_handler(
                    servicer.SayHellosServerStreaming,
                    request_deserializer=hello__service__pb2.HelloRequest.FromString,
                    response_serializer=hello__service__pb2.HelloResponse.SerializeToString,
            ),
            'SayHellosClientStreaming': grpc.stream_unary_rpc_method_handler(
                    servicer.SayHellosClientStreaming,
                    request_deserializer=hello__service__pb2.HelloRequest.FromString,
                    response_serializer=hello__service__pb2.HelloResponse.SerializeToString,
            ),
            'SayHellosBidirectional': grpc.stream_stream_rpc_method_handler(
                    servicer.SayHellosBidirectional,
                    request_deserializer=hello__service__pb2.HelloRequest.FromString,
                    response_serializer=hello__service__pb2.HelloResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'hello.MultilingualGreeter', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('hello.MultilingualGreeter', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MultilingualGreeter(object):
    """The greeting service definition.
    """

    @staticmethod
    def SayHello(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hello.MultilingualGreeter/SayHello',
            hello__service__pb2.HelloRequest.SerializeToString,
            hello__service__pb2.HelloResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SayHellosServerStreaming(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/hello.MultilingualGreeter/SayHellosServerStreaming',
            hello__service__pb2.HelloRequest.SerializeToString,
            hello__service__pb2.HelloResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SayHellosClientStreaming(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/hello.MultilingualGreeter/SayHellosClientStreaming',
            hello__service__pb2.HelloRequest.SerializeToString,
            hello__service__pb2.HelloResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SayHellosBidirectional(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/hello.MultilingualGreeter/SayHellosBidirectional',
            hello__service__pb2.HelloRequest.SerializeToString,
            hello__service__pb2.HelloResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
