# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: hello_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'hello_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13hello_service.proto\x12\x05hello\"L\n\x0cHelloRequest\x12\x12\n\nfirst_name\x18\x01 \x01(\t\x12\x11\n\tlast_name\x18\x02 \x01(\t\x12\x15\n\rlanguage_code\x18\x03 \x01(\t\"!\n\rHelloResponse\x12\x10\n\x08greeting\x18\x01 \x01(\t2\xaf\x02\n\x13MultilingualGreeter\x12\x37\n\x08SayHello\x12\x13.hello.HelloRequest\x1a\x14.hello.HelloResponse\"\x00\x12I\n\x18SayHellosServerStreaming\x12\x13.hello.HelloRequest\x1a\x14.hello.HelloResponse\"\x00\x30\x01\x12I\n\x18SayHellosClientStreaming\x12\x13.hello.HelloRequest\x1a\x14.hello.HelloResponse\"\x00(\x01\x12I\n\x16SayHellosBidirectional\x12\x13.hello.HelloRequest\x1a\x14.hello.HelloResponse\"\x00(\x01\x30\x01\x42,\n\x0e\x63om.grpc.helloB\x0fHelloWorldProtoP\x01\x90\x01\x01\xa2\x02\x03HLWb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'hello_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\016com.grpc.helloB\017HelloWorldProtoP\001\220\001\001\242\002\003HLW'
  _globals['_HELLOREQUEST']._serialized_start=30
  _globals['_HELLOREQUEST']._serialized_end=106
  _globals['_HELLORESPONSE']._serialized_start=108
  _globals['_HELLORESPONSE']._serialized_end=141
  _globals['_MULTILINGUALGREETER']._serialized_start=144
  _globals['_MULTILINGUALGREETER']._serialized_end=447
_builder.BuildServices(DESCRIPTOR, 'hello_service_pb2', _globals)
# @@protoc_insertion_point(module_scope)
